export const AuthActionType = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
};

export const ProductsActionType = {
  GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAIL: 'GET_PRODUCT_FAIL',
};

export const ProductDetailActionType = {
  GET_PRODUCT_DETAIL_REQUEST: 'GET_PRODUCT_DETAIL_REQUEST',
  GET_PRODUCT_DETAIL_SUCCESS: 'GET_PRODUCT_DETAIL_SUCCESS',
  GET_PRODUCT_DETAIL_FAIL: 'GET_PRODUCT_DETAIL_FAIL',
};

export const CategoryType = {
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
  GET_CATEGORY_FAIL: 'GET_CATEGORY_FAIL',
};

export const UserAdminType = {
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAIL: 'GET_USERS_FAIL',
  ADD_NEW_USER_SUCCESS: 'ADD_NEW_USER_SUCCESS',
  ADD_NEW_USER_FAIL: 'ADD_NEW_USER_FAIL',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
};

export const ManufacturerAdminType = {
  GET_MANUFACTURER_REQUEST: 'GET_MANUFACTURER_REQUEST',
  GET_MANUFACTURER_SUCCESS: 'GET_MANUFACTURER_SUCCESS',
  GET_MANUFACTURER_FAIL: 'GET_MANUFACTURER_FAIL',
  ADD_MANUFACTURER: 'ADD_MANUFACTURER',
  UPDATE_MANUFACTURER: 'UPDATE_MANUFACTURER',
};

export const AddressAdminType = {
  GET_ADDRESS_REQUEST: 'GET_ADDRESS_REQUEST',
  GET_ADDRESS_SUCCESS: 'GET_ADDRESS_SUCCESS',
  GET_ADDRESS_FAIL: 'GET_ADDRESS_FAIL',
};
